### ISSUE TITLE
Database redesign?

### ISSUE THREAD

**Issue by ZavierHenry** [klinker24/talon-for-twitter-android#102]
So I was going to attempt to resolve #38 by first adding a is_verified column to the different tables. But looking at the different tables, there seems to be a lot of data redundancies. Would you consider a change to the database tables to reduce these dependencies? It would also be easier to update the table columns in the future

**Comment by klinker24** [comment]
You can take a stab at it, if you want. I admit that I knew absolutely nothing about databases when I created it 6 years ago. Everything is in separate databases, rather than tables. It is messy, but it works fine, so I haven't changed it. 

If you do this, it will need to be a transparent migration for users, we cannot just clear all the tables and start from scratch, which is the biggest challenge.

This is not something that I will be doing for the app though, no.
